objects/Pen__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Enter customer name</inlineHelpText>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pen_Cost__c</fullName>
        <label>Pen Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pen</label>
    <nameField>
        <label>Pen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShowPen.cls
public class ShowPen {
    public List<pen__C> Pen {get;set;}
    public account account;
    
    public showPen()
    {
        Pen = [select id, name,Customer_Name__c, Pen_Cost__c, Comments__c from pen__C];
        
    }
    
    public pagereference updatepen()
    {
        update Pen;
        //redirection to VPFAccountPage
        account = [select id from account where name = 'Cognizant' limit 1];
        Pagereference pgr = new Pagereference('/apex/VFPAccount?id' + account.id );
        return pgr;
    }
    
       

}