objects/Pen__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pen_Cost__c</fullName>
        <label>Pen Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pen</label>
    <nameField>
        <label>Pen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PenDiscount.cls
public class PenDiscount {
    
     public static void fnupddiscount(list<Pen__C> Penlist)
    {
      if(trigger.isbefore == true && trigger.isupdate == true)  
            for (Pen__c P: Penlist)
            {
            if(P.Pen_Cost__c > 100)
            {
            P.Pen_cost__c = P.Pen_cost__c - 20;
            }
            }   
       if(trigger.isbefore == true && trigger.isinsert == true)
        {        
            for (Pen__c P: Penlist)
            {        
            P.Comments__c = 'Newly Created Pen Record';        
            }    
            system.debug('Before insert function got called');
            
        }  
        if(trigger.isbefore == true && trigger.isupdate == true)
        {        
            for (Pen__c P: Penlist)
            {        
            P.Comments__c = 'Pen Records is updated';        
            }    
            system.debug('Before update function is called');
            
        } 
        
    }   
    
}