objects/Pen__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Enter customer name</inlineHelpText>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pen_Class__c</fullName>
        <formula>IF(Pen_Cost__c = 0, 'Promotion',  IF( AND(Pen_Cost__c &gt;0 ,  Customer_Name__c  = 'hp') , 'Premium', 'Paid') )</formula>
        <label>Pen Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pen_Cost__c</fullName>
        <label>Pen Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pen</label>
    <nameField>
        <label>Pen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PenSearchList.cls
public with sharing class PenSearchList {    
    
    @AuraEnabled
    public static list<sobject> searchpen(string input1)        
    {  
        string condition =        '%'+input1+'%' ;
        system.debug('condition is ' + condition);
        
        if(input1 != null)
        {
        string query = 'select id,name,Pen_Cost__c, Pen_Class__c, Customer_Name__c from pen__C where name like :condition';
        system.debug(query);
        List<sobject> oPen = database.query(query);       
        return oPen;
        }
        else
        {
        string query = 'select id,name,Pen_Cost__c, Pen_Class__c, Customer_Name__c from pen__C LIMIT 8';
            system.debug(query);
        List<sobject> oPen = database.query(query);       
        return oPen;
        }
        
        
        
    }  
    
}