objects/Pen__c.object
<CustomObject>
    <fields>
        <fullName>Pen_Cost__c</fullName>
        <label>Pen Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pen</label>
    <nameField>
        <label>Pen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PenDiscountV1.cls
public class PenDiscountV1 {
    
    
    public static void fnapplydiscount(List<Pen__C> Penlist)
    {
     /*   for(Pen__C P : Penlist)
    {
        if(P.Pen_cost__C > 100 &&  P.Pen_Cost__C < 200)        {
            P.Pen_cost__C = P.Pen_cost__C - 20;
        }
        else if(P.Pen_cost__C > 50  && P.Pen_cost__C < 100)        {
            P.Pen_cost__C = P.Pen_cost__C - 10;
        }
        else if(P.Pen_cost__C < 50 && P.Pen_cost__C > 10)        {
            P.Pen_cost__C = P.Pen_cost__C - 5;
        }
        else if (P.Pen_cost__C < 10)        {
            P.Pen_Cost__c.addError('Price of the Pen is too low.Kindly add a value bigger that 10');
            
        }
        }*/  
        
    } 

  public static void fnapplydiscountupdate(List<Pen__C> Penlist)
  {
      
      for (Pen__C P : Penlist)
      {
        if (P.Pen_Cost__c>100)  
            P.Pen_Cost__c = P.Pen_Cost__c - 20;
      }
      
  }

    

}